### ISSUE TITLE
Pixel mask with only one pixel

### ISSUE THREAD

**Issue by valboz** [jvc2688/K2-CPM#5]
It seems that the code does not work when a single pixel is specified in the pixel mask file.

If the file is imported with pixel_list = np.loadtxt(args.pixel, dtype=int), 
then pixel_list is created as a one-dimensional array of size 2 if there is only one pixel. This is wrong and creates problems afterwards.

**Comment by rpoleski** [comment]
`pixel_list = np.loadtxt(args.pixel, dtype=int, ndmin=2)` should work fine.

**Comment by jvc2688** [comment]
I've fixed the issue with @rpoleski 's method
